### PR TITLE
Feature deploy image

### PR DESCRIPTION
**Pull request by simbarras**
For the issue #2, I improve the go version management and I add a workflow to build images

### CODE REVIEW

**Comment by simbarras** [comment]
If you want to merge my PR, can you add this tag "hacktoberfest-accepted" ?

**Comment by jheise** [comment]
Sure! Just tag it at the main repo level?

**Comment by simbarras** [comment]
No, it's in Pull request tag. Details is here: https://hacktoberfest.com/participation/

**Comment by simbarras** [comment]
Thank's !

**Pull request merged**
